
// completion_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionMessage struct {
    Role string `json:"role"`
    Content []string `json:"content"`
}

