
// completion_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionCollection struct {
    Object string `json:"object"`
    Data []CompletionResponse `json:"data"`
    FirstId string `json:"first_id"`
    LastId string `json:"last_id"`
    HasMore bool `json:"has_more"`
}

