
// completion_message_user automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionMessageUser struct {
    Role string `json:"role"`
    Content string `json:"content"`
    Name string `json:"name"`
}

