
// completion_message_assistant automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionMessageAssistant struct {
    Role string `json:"role"`
    Content []string `json:"content"`
    Audio string `json:"audio"`
    Name string `json:"name"`
    Refusal string `json:"refusal"`
    ToolCalls []string `json:"tool_calls"`
}

