
// completion_choice automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionChoice struct {
    Index int `json:"index"`
    Message *CompletionMessage `json:"message"`
    FinishReason string `json:"finish_reason"`
}

