
// completion_tokens_details automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionTokensDetails struct {
    AcceptedPredictionTokens int `json:"accepted_prediction_tokens"`
    AudioTokens int `json:"audio_tokens"`
    ReasoningTokens int `json:"reasoning_tokens"`
    RejectedPredictionTokens int `json:"rejected_prediction_tokens"`
}

