
// completion_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionResponse struct {
    Id string `json:"id"`
    Object string `json:"object"`
    Created int `json:"created"`
    Model string `json:"model"`
    Choices []CompletionChoice `json:"choices"`
    Usage *CompletionUsage `json:"usage"`
    ServiceTier string `json:"service_tier"`
    SystemFingerprint string `json:"system_fingerprint"`
}

