
// completion_message_tool automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionMessageTool struct {
    Role string `json:"role"`
    Content []string `json:"content"`
    ToolCallId string `json:"tool_call_id"`
}

