
// completion_usage automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionUsage struct {
    CompletionTokens int `json:"completion_tokens"`
    PromptTokens int `json:"prompt_tokens"`
    TotalTokens int `json:"total_tokens"`
    CompletionTokensDetails *CompletionTokensDetails `json:"completion_tokens_details"`
    PromptTokensDetails *PromptTokensDetails `json:"prompt_tokens_details"`
}

