
// completion_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionRequest struct {
    Model string `json:"model"`
    Messages []CompletionMessage `json:"messages"`
    FrequencyPenalty float64 `json:"frequency_penalty"`
    LogitBias map[string]int `json:"logit_bias"`
    Logprobs bool `json:"logprobs"`
    MaxCompletionTokens int `json:"max_completion_tokens"`
    Metadata map[string]string `json:"metadata"`
    PresencePenalty float64 `json:"presence_penalty"`
    ReasoningEffort string `json:"reasoning_effort"`
    Seed int `json:"seed"`
    ServiceTier string `json:"service_tier"`
    Stop []string `json:"stop"`
    Store bool `json:"store"`
    Temperature float64 `json:"temperature"`
    TopLogprobs int `json:"top_logprobs"`
    TopP float64 `json:"top_p"`
    User string `json:"user"`
}

