
// completion_deleted automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CompletionDeleted struct {
    Object string `json:"object"`
    Id string `json:"id"`
    Deleted bool `json:"deleted"`
}

