
// error_detail automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ErrorDetail struct {
    Type string `json:"type"`
    Message string `json:"message"`
}

