
// prompt_tokens_details automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type PromptTokensDetails struct {
    AudioTokens int `json:"audio_tokens"`
    CachedTokens int `json:"cached_tokens"`
}

