
// response_mcp_tool automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseMCPTool struct {
    InputSchema any `json:"input_schema"`
    Name string `json:"name"`
    Annotations map[string]string `json:"annotations"`
    Description string `json:"description"`
}

