
// response_request_input_function_call_output automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



// The output of a function tool call.
type ResponseRequestInputFunctionCallOutput struct {
    Type string `json:"type"`
    CallId string `json:"call_id"`
    Output string `json:"output"`
    Id string `json:"id"`
    Status string `json:"status"`
}

