
// response_text automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseText struct {
    Format *ResponseTextFormat `json:"format"`
    Verbosity string `json:"verbosity"`
}

