
// response_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseRequest struct {
    Background bool `json:"background"`
    Conversation *ResponseRequestConversation `json:"conversation"`
    Include []string `json:"include"`
    Input string `json:"input"`
    Instructions string `json:"instructions"`
    MaxOutputTokens string `json:"max_output_tokens"`
    MaxToolCalls string `json:"max_tool_calls"`
    Metadata map[string]string `json:"metadata"`
    Model string `json:"model"`
    ParallelToolCalls bool `json:"parallel_tool_calls"`
    PreviousResponseId string `json:"previous_response_id"`
    Prompt *ResponsePrompt `json:"prompt"`
    PromptCacheKey string `json:"prompt_cache_key"`
    Reasoning *ResponseReasoning `json:"reasoning"`
    SafetyIdentifier string `json:"safety_identifier"`
    ServiceTier string `json:"service_tier"`
    Store bool `json:"store"`
    Temperature float64 `json:"temperature"`
    Text *ResponseText `json:"text"`
    ToolChoice string `json:"tool_choice"`
    Tools []ResponseTool `json:"tools"`
    TopLogprobs int `json:"top_logprobs"`
    TopP float64 `json:"top_p"`
    Truncation string `json:"truncation"`
}

