
// response_request_text automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseRequestText struct {
    Format *ResponseRequestTextFormat `json:"format"`
    Verbosity string `json:"verbosity"`
}

