
// response_request_input_mcp_list_tools automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



// A list of tools available on an MCP server.
type ResponseRequestInputMcpListTools struct {
    Type []ResponseMCPTool `json:"type"`
    Id string `json:"id"`
    ServerLabel string `json:"server_label"`
    Tools string `json:"tools"`
    Error string `json:"error"`
}

