
// response_request_conversation automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseRequestConversation struct {
    Id string `json:"id"`
}

