
// response_tool_function automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseToolFunction struct {
    Type string `json:"type"`
    Name string `json:"name"`
    Parameters any `json:"parameters"`
    Strict bool `json:"strict"`
    Description string `json:"description"`
}

