
// response_response_output_function_call automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseResponseOutputFunctionCall struct {
    Type string `json:"type"`
    Arguments string `json:"arguments"`
    CallId string `json:"call_id"`
    Name string `json:"name"`
    Id string `json:"id"`
    Status string `json:"status"`
}

