
// response_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseResponse struct {
    CreatedAt int `json:"created_at"`
    Error *ResponseResponseError `json:"error"`
    Id string `json:"id"`
    IncompleteDetails string `json:"incomplete_details"`
    Object string `json:"object"`
    Output []ResponseResponseOutput `json:"output"`
    PreviousResponseId string `json:"previous_response_id"`
}

