
// response_response_output_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



// An output message from the model.
type ResponseResponseOutputMessage struct {
    Type string `json:"type"`
    Content []string `json:"content"`
    Id string `json:"id"`
    Role string `json:"role"`
    Status string `json:"status"`
}

