
// response_request_text_format_json_schema automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseRequestTextFormatJsonSchema struct {
    Type string `json:"type"`
    Name string `json:"name"`
    Schema any `json:"schema"`
    Description string `json:"description"`
    Strict bool `json:"strict"`
}

