
// response_tool_web_search automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseToolWebSearch struct {
    Type string `json:"type"`
    Filters *ResponseToolWebSearchFilter `json:"filters"`
    SearchContextSize string `json:"search_context_size"`
    UserLocation *ResponseToolWebSearchLocation `json:"user_location"`
}

