
// response_request_text_format automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseRequestTextFormat struct {
    Type string `json:"type"`
}

