
// response_tool_mcp automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseToolMCP struct {
    Type string `json:"type"`
    ServerLabel string `json:"server_label"`
    AllowedTools []string `json:"allowed_tools"`
    Authorization string `json:"authorization"`
    ConnectorId string `json:"connector_id"`
    Headers map[string]string `json:"headers"`
    RequireApproval string `json:"require_approval"`
    ServerDescription string `json:"server_description"`
    ServerUrl string `json:"server_url"`
}

