
// response_reasoning automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseReasoning struct {
    Effort string `json:"effort"`
    Summary string `json:"summary"`
}

