
// response_tool_web_search_location automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseToolWebSearchLocation struct {
    City string `json:"city"`
    Country string `json:"country"`
    Region string `json:"region"`
    Timezone string `json:"timezone"`
    Type string `json:"type"`
}

