
// response_request_text_format_text automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseRequestTextFormatText struct {
    Type string `json:"type"`
}

