
// response_request_tool_function automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



// Defines a function in your own code the model can choose to call.
type ResponseRequestToolFunction struct {
    Type string `json:"type"`
    Name string `json:"name"`
    Parameters any `json:"parameters"`
    Strict bool `json:"strict"`
    Description string `json:"description"`
}

