
// response_response_output automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseResponseOutput struct {
    Type string `json:"type"`
}

