
// response_prompt automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponsePrompt struct {
    Id string `json:"id"`
    Variables map[string]string `json:"variables"`
    Version string `json:"version"`
}

