
// response_request_input_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseRequestInputMessage struct {
    Type string `json:"type"`
    Content string `json:"content"`
    Role string `json:"role"`
}

