
// response_tool_web_search_filter automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ResponseToolWebSearchFilter struct {
    AllowedDomains []string `json:"allowed_domains"`
}

