
// response_request_input automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



// An item representing part of the context for the response to be generated by the model. Can contain text, images, and audio inputs, as well as previous assistant responses and tool call outputs.
type ResponseRequestInput struct {
    Type string `json:"type"`
}

